name: General Issue
description: Bug / Feature / Task 공용 이슈 템플릿
title: "[Type] 제목을 입력하세요"
labels: []
assignees: []

body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: 이슈의 유형을 선택하세요
      options:
        - Bug
        - Feature
        - Task / Refactor
        - Docs
    validations:
      required: true

  - type: input
    id: summary
    attributes:
      label: Summary
      description: 어떤 문제/요구사항인지 한 줄 요약
      placeholder: "예: 단축키 동작 안함"

  - type: textarea
    id: details
    attributes:
      label: Details
      description: 배경, 의도, 제약사항 등 자세한 설명
      placeholder: "상세 설명을 입력하세요"

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Logs
      description: 스크린샷, 콘솔/Crash 로그 첨부
      placeholder: "이미지 또는 로그 붙여넣기"

  - type: checkboxes
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: 이슈 완료 조건
      options:
        - label: 조건 1
        - label: 조건 2

  - type: textarea
    id: etc
    attributes:
      label: ETC
      description: 관련 이슈/PR, 참고 링크 등
      placeholder: "추가 참고사항"